### ISSUE TITLE
Error: failed to load modules: module "github.com/basa-casa/hugo-scms-admin" not found

### ISSUE THREAD

**Issue by myuksektepe** [basa-casa/hugo-module-bc-nc-admin#8]
Hi,
I'm following https://github.com/basa-casa/hugo-admin#installation but I facing a problem;

I have **hugo v0.126.1+extended** and there is no config.toml/.yml/.json file in the folder.  There is just **hugo.toml** and when i add these below lines

```
[module]
    [[module.imports]]
        path = "github.com/basa-casa/hugo-scms-admin"
```

into this file and run `hugo mod vendor ` command i get this error:

`Error: failed to load modules: module "github.com/basa-casa/hugo-scms-admin" not found in "..../hugo/quickstart/themes/github.com/basa-casa/hugo-scms-admin"; either add it as a Hugo Module or store it in "..../hugo/quickstart/themes".: module does not exist`

what did i do wrong? 🙄

**Comment by bmackinney** [comment]
I'm sorry Murat the instructions weren't correct and I wasn't paying attention. Want to try again?
